import Navbar from "@/components/ui/Navbar";
import TanstackProvider from "@/providers/TanstackProvider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black dark:text-white bg-white`}
      >
        <TanstackProvider>
          <section className="max-w-7xl mx-auto px-10 lg:px-0">
            <Navbar />
            {children}
          </section>
        </TanstackProvider>
      </body>
    </html>
  );
}
export default RootLayout;
